# Generated by Django 5.0.4 on 2024-04-25 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_roles_id_alter_user_id_alter_userprofiles_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='checked',
        ),
        migrations.CreateModel(
            name='IsUmadjaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.user')),
            ],
        ),
    ]
