# Generated by Django 5.0.4 on 2024-04-25 02:28

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_user_checked_isumadjaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profiles/pictures/default.jpg', upload_to='profiles/pictures/profiles/'),
        ),
    ]
