# Generated by Django 5.0.4 on 2024-04-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/pictures/profiles/'),
        ),
    ]
