# Generated by Django 5.0.4 on 2024-04-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='profule_picture',
            field=models.ImageField(default='profiles/pictures/default.jpg', upload_to='profiles/pictures/profiles_/'),
        ),
    ]
