# Generated by Django 5.0.4 on 2024-04-25 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isumadjaf',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.user', unique=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.user', unique=True),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.user', unique=True),
        ),
    ]
