# Generated by Django 5.0.4 on 2024-04-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_isumadjaf_user_id_alter_roles_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofiles',
            old_name='profule_picture',
            new_name='profile_picture',
        ),
    ]
