# Generated by Django 5.0.6 on 2024-05-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
