# Generated by Django 5.0.6 on 2024-05-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_isumadjaf_user_id_alter_userprofiles_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsUmadjaf',
        ),
    ]
