# Generated by Django 5.0.6 on 2024-05-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_delete_isumadjaf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroles',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='UserProfiles',
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
