# Generated by Django 5.0.6 on 2024-05-25 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_alter_user_password_alter_userprofiles_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.user'),
        ),
    ]
