# Generated by Django 5.0.6 on 2024-05-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='bio',
            field=models.TextField(max_length=75),
        ),
    ]
