# Generated by Django 5.0.6 on 2024-05-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_alter_userprofiles_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='church',
            field=models.IntegerField(),
        ),
    ]
