# Generated by Django 5.0.6 on 2024-05-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_alter_user_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='church',
            field=models.CharField(max_length=100),
        ),
    ]
