# Generated by Django 5.0.6 on 2024-05-29 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_alter_user_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='role_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.roles'),
        ),
    ]
