# Generated by Django 5.0.6 on 2024-05-29 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_alter_userroles_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isumadjaf',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='role_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='profiles.roles'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
