# Generated by Django 5.0.6 on 2024-05-29 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_alter_isumadjaf_user_id_alter_userprofiles_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isumadjaf',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='role_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.roles'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
