# Generated by Django 5.0.6 on 2024-05-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_alter_isumadjaf_user_id_alter_userprofiles_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='church',
            field=models.ImageField(upload_to=''),
        ),
    ]
