# Generated by Django 5.0.6 on 2024-05-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_alter_user_church'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='church',
            field=models.IntegerField(),
        ),
    ]
