# Generated by Django 5.0.7 on 2024-07-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofiles_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_phone',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
