# Generated by Django 5.0.7 on 2024-07-22 13:55

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0004_delete_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('hours', models.TimeField()),
                ('theme', models.TextField(default='')),
                ('is_general', models.BooleanField(default=False)),
                ('logo', models.ImageField(default='calendar/default.jpg', upload_to=events.models.get_upload_to_calendar)),
                ('background', models.ImageField(default='calendar/default.jpg', upload_to=events.models.get_upload_to_calendar)),
                ('author_id', models.IntegerField(default=0)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.congregations')),
            ],
        ),
    ]
