# Generated by Django 5.0.7 on 2024-07-22 15:07

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='background',
            field=models.ImageField(default='events/default.jpg', upload_to=events.models.get_upload_to_calendar),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(default='events/default.jpg', upload_to=events.models.get_upload_to_calendar),
        ),
    ]
