# Generated by Django 5.0.6 on 2024-05-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='articles/default.jpg', upload_to='articles/'),
        ),
    ]
