# Generated by Django 5.0.7 on 2024-07-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_not_umadjaf',
            field=models.BooleanField(default=False),
        ),
    ]
