# Generated by Django 5.0.7 on 2024-07-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_is_not_umadjaf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='is_not_umadjaf',
            new_name='post_unlock',
        ),
    ]
