# Generated by Django 5.0.7 on 2024-07-23 18:54

import django.db.models.deletion
import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(default=0)),
                ('event_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author_id', models.IntegerField(default=0)),
                ('image', models.ImageField(default='gallery/default.jpg', upload_to=gallery.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryMarked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryMarkedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('gallery_marked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_users', to='gallery.gallerymarked')),
            ],
        ),
    ]
