# Generated by Django 5.0.7 on 2024-07-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymarkeduser',
            name='marked_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
