# Generated by Django 5.0.7 on 2024-07-23 01:04

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='carrousel/default.jpg', upload_to=home.models.get_upload_to_carrousel)),
                ('active', models.BooleanField(default=False)),
                ('author_id', models.IntegerField(default=0)),
            ],
        ),
    ]
