# Generated by Django 5.0.7 on 2024-07-23 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_nada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nada',
        ),
    ]
