# Generated by Django 5.0.7 on 2024-07-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_description_carrousel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrousel',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
