# Generated by Django 5.0.7 on 2024-07-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_carrousel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrousel',
            name='link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
