# Generated by Django 5.0.6 on 2024-06-03 18:22

import django.db.models.deletion
import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('theme', models.TextField(default='')),
                ('logo', models.ImageField(default='calendar/default.jpg', upload_to='calendar/')),
                ('background', models.ImageField(default='calendar/default.jpg', upload_to='calendar/')),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.congregations')),
            ],
        ),
    ]
