# Generated by Django 5.0.6 on 2024-05-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_congregations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregations',
            name='address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
