# Generated by Django 5.0.7 on 2024-07-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
