# Generated by Django 5.0.6 on 2024-05-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_congregations_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Congregations',
        ),
    ]
