# Generated by Django 5.0.7 on 2024-07-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_calendar_is_general'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
