# Generated by Django 5.0.6 on 2024-05-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0004_delete_congregations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congregations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('area', models.CharField(max_length=200)),
            ],
        ),
    ]
