# Generated by Django 5.0.6 on 2024-05-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_congregations_address_alter_congregations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregations',
            name='address',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='congregations',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
