# Generated by Django 5.0.6 on 2024-05-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_congregations_address_alter_congregations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congregations',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='congregations',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
